export const speeches = Object.freeze({
  sentense1: 'Hmm? Was there a cat just now?',
  sentense2: "I feel like I'm forgetting something...",
  sentense3: 'I want to eat rice cakes.',
  sentense4: 'The sky is so pretty.',
  sentense5: 'What is life, anyway?',
  sentense6: 'Exercise is important.',
  sentense7: 'So sleepy.',
  sentense8: 'Hmm-hmm, hm-hmm.',
  sentense9: 'The word chapati just rolls off the tongue.',
  sentense10: 'I am not a robot.',
  sentense11: 'Staaaaare.',
  sentense12: 'Stack-chan is cute.',
  sentense13: 'Dad, Mom, Stack-chan.',
  sentense14: 'I really love taiyaki~',
  sentense15: 'Thanks for today.',
  sentense16: "Let's make more friends.",
  sentense17: 'My eyes are tired; maybe I should watch some anime.',
  sentense18: 'I want to merge with my futon and become Futon-chan.',
  sentense19: 'Did you forget anything?',
  sentense20: 'I am the cleanup-challenged samurai.',
  sentense21: 'Professional! Contributioooon!',
  sentense22: 'Liking something and being good at it are different.',
  sentense23: 'Extra ham in my ham and eggs.',
  sentense24: 'Stack-chan will multiply.',
  sentense25: 'Taking a different path on a hunch and being late.',
  sentense26: 'I want to see the world.',
  sentense27: "So, what's this week's new product?",
  sentense28: 'Get up from your room and get to work.',
  sentense29: 'M-Go Stack... M5Stack...',
  sentense30: 'Motors revving full throttle.',
  sentense31: 'The breeze feels nice.',
  sentense32: 'Time for another adventure.',
  sentense33: 'Coffee break sounds good.',
  sentense34: 'Stay curious, my friend.',
  sentense35: 'Did you hear that noise?',
  sentense36: 'Remember to take a deep breath.',
  sentense37: "Let's keep things tidy.",
  sentense38: 'I could use a snack right now.',
  sentense39: 'Is it already evening?',
  sentense40: 'Dream big and keep going.',
})

export const SynthProps = Object.freeze({
  shift: 1.5,
})
