export const speeches = Object.freeze({
  sentense1: 'ん？いまネコいた？',
  sentense2: 'なんか忘れてる気がする…。',
  sentense3: 'おもち食べたい。',
  sentense4: 'お空きれいだな。',
  sentense5: '人生ってなんだろう？',
  sentense6: '運動は大事。',
  sentense7: 'ねむみ。',
  sentense8: 'フンフン、フフーン。',
  sentense9: 'チャパティって響き、何度でも口に出していきたい。',
  sentense10: '私はロボットではありません。',
  sentense11: 'じーーー。',
  sentense12: 'ｽﾀｯｸﾁｬﾝはかわいい。',
  sentense13: 'ちち、はは、ｽﾀｯｸﾁｬﾝ。',
  sentense14: '好き好きたいやき〜。',
  sentense15: '今日もありがとね。',
  sentense16: '仲間をふやしていきたいね。',
  sentense17: '目が疲れたからアニメでも見るか。',
  sentense18: 'オフトゥンと合体したい。オフトゥンチャンになる。',
  sentense19: '忘れ物ない？',
  sentense20: '拙者、お片付け苦手侍でござる。',
  sentense21: 'プロフェッショナル！コントリビューーーション！',
  sentense22: '好きと得意は違うよね。',
  sentense23: 'ハムエッグのハム増量。',
  sentense24: 'ｽﾀｯｸﾁｬﾝは増えます。',
  sentense25: '調べたルートと異なる道を、勘で歩いて遅刻する。',
  sentense26: '世界を見てみたいな〜。',
  sentense27: 'さーて、今週の新製品は？',
  sentense28: '部屋から立ち上がってお仕事しようね。',
  sentense29: 'エムゴスタック…エムファイブスタック…。',
  sentense30: 'モーターぎゅんぎゅん。',
  sentense31: '風が気持ちいいね。',
  sentense32: '今日はお出かけ日和かな？',
  sentense33: 'ちょっと休憩しよう。',
  sentense34: '好きな食べ物はなに？',
  sentense35: 'そろそろ寝てもいい？',
  sentense36: 'うーん、考え中。',
  sentense37: '忙しい時ほど深呼吸。',
  sentense38: '時間が経つの早いね。',
  sentense39: 'まったりするのも大事。',
  sentense40: 'いつもありがとう！',
})

export const SynthProps = Object.freeze({
  shift: 1.5,
})
